insert into user_type(id,parentid,name,color) values(1,null,'Warrior','red');
insert into user_type(id,parentid,name,color) values(2,null,'Wizard','green');
insert into user_type(id,parentid,name,color) values(3,null,'Priest','white');
insert into user_type(id,parentid,name,color) values(4,null,'Rogue','yellow');
insert into user_type(id,parentid,name,color) values(5,1,'Fighter','blue');
insert into user_type(id,parentid,name,color) values(6,1,'Paladin','lighblue');
insert into user_type(id,parentid,name,color) values(7,1,'Ranger','lighgreen');
insert into user_type(id,parentid,name,color) values(8,2,'Mage','grey');
insert into user_type(id,parentid,name,color) values(9,2,'Specialist wizard','lightgrey');
insert into user_type(id,parentid,name,color) values(10,3,'Cleric','red');
insert into user_type(id,parentid,name,color) values(11,3,'Druid','green');
insert into user_type(id,parentid,name,color) values(12,3,'Priest of specific mythos','white');
insert into user_type(id,parentid,name,color) values(13,4,'Thief','yellow');
insert into user_type(id,parentid,name,color) values(14,4,'Bard','blue');
insert into user_type(id,parentid,name,color) values(15,13,'Assassin','lighblue');